### ISSUE TITLE
Z Home Retract is too low

### ISSUE THREAD

**Issue by pomeroyb** [pomeroyb/MarlinForKilo#1]
Change the following line:
https://github.com/pomeroyb/MarlinForKilo/blob/master/Marlin/Configuration_adv.h#L218

2mm is obviously too small. 15 is probably too much. 10 might be just right, but we'll have to ask Goldilocks.

**Comment by pomeroyb** [comment]
If this issue is solved, it should be closed...

**Comment by ALAN3D** [comment]
Changed to 10mm from 2mm. A little high but will be lowered and dialed in after further testing.
